### PR TITLE
Add python3 support

### PR DESCRIPTION
**Pull request by chrisburr**
This branch makes a few minor changes to enable the framework to be ran with either python2 or python3. It's up to you guys if you want to keep this included or close it without merging.

### CODE REVIEW

**Comment by alexpearce** [comment]
Yep I'm all for it :snake:. How did you find what needed changing?

That means we'll need to add Python 3 to the [Travis configuration](https://github.com/alexpearce/CharmProduction/blob/42232d403dac31da114953126f9f034a7f612ee4/.travis.yml), which ultimately means  compiling ROOT with Python 3 on Travis. I have a [repository that builds ROOT in Travis-like environment](https://github.com/alexpearce/travis-ci-root-builds), but when I briefly tried to get Python 3 in the loop I ran in to trouble setting up the virtual environments. I can give it another go.

**Comment by alexpearce** [comment]
Also, I guess ≥ 3.3?

**Comment by chrisburr** [comment]
On my desktop I get root from the [AUR](https://aur.archlinux.org/packages/root/) which builds it for Python 3 so I kept running it until it worked. The [cmake arugments](https://aur.archlinux.org/packages/ro/root/PKGBUILD) they use [need changing](https://root.cern.ch/drupal/content/building-root-cmake#options) to use `builtin_xrootd`, `roofit` and maybe some others.

Prior to the current dev branch of ROOT a patch was needed but it now appears to build cleanly, I can give it a try basing it off your repository if you want.

**Comment by chrisburr** [comment]
And I'm on 3.4.2, I'm not sure how far back support goes.

**Comment by alexpearce** [comment]
You run Arch? Hardcore, man! :penguin: 

Maybe that's the problem, I'm building 6.02.4 and 5.24.25. Is there a released version that at least should work for Python 3?

**Comment by chrisburr** [comment]
I think there is the "dev" release [6.03/02](https://root.cern.ch/drupal/content/downloading-root).

**Comment by alexpearce** [comment]
The `print` statements in `reprocess_2010_ntuples.py` will need to use the `print` function. (There are also some Python scripts in BDTTools/ that use the statement.)

**Comment by chrisburr** [comment]
I've updated `reprocess_2010_ntuples.py`.

@dominikmuller Are any of the python scripts in BDTTools being used?

**Comment by alexpearce** [comment]
Are we retaining Python 2(.7) compatibility as well? I would like to. If so we should use `from __future__ import print_function`.

**Comment by chrisburr** [comment]
I think we definitely need to keep Python 2.7 support, I'm not sure its even practical to get python 3 to run on managed SLC6 machines.

I have only just realised that `print(s)` is printing a tuple in Python 2 - fixed.

**Comment by alexpearce** [comment]
I'm just building ROOT with Python 3.4, takes ~ 30 minutes on my VM per build so bear with me. Once that's done and tested we can add it to the Travis config here.

**Comment by dominikmuller** [comment]
@chrisburr As far as I know no, they are not. We might move the rootTeX script somewhere as it is the standalone version.

**Comment by alexpearce** [comment]
I've [added Python 3 builds](https://github.com/alexpearce/travis-ci-root-builds/commit/7337d88c9b8aed4f130bdcc89495559dac1f7f8c) and the [tests are passing](https://travis-ci.org/alexpearce/test-travis-builds/builds/50028001) (after an [initial blunder](https://github.com/alexpearce/test-travis-builds/commit/a0bc219de15719e010d717cbcab3512433fb19e7)).

Could you add this patch to this PR to check the tests and stuff?

```patch
diff --git a/.travis.yml b/.travis.yml
index a4b6cd5..71f7f5d 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,8 +1,13 @@
 language: python
-python: 2.7
+# Python versions to test
+python:
+  - "2.7"
+  - "3.3"
+  - "3.4"
 # ROOT versions to test
 env:
-  - ROOT_VERSION=6.02.04
+  - ROOT_VERSION=5.34.25
+  - ROOT_VERSION=6.03.02
 # Install GCC 4.8, required for ROOT 6
 before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
```

**Comment by chrisburr** [comment]
Are we putting ROOT5 back in then?

**Comment by alexpearce** [comment]
Well… The Python module should work with ROOT 5, I don't think I've done anything 6-specific. I know the BDT tools do.

I guess we're all running 6, so we don't really need to test with 5.

**Comment by chrisburr** [comment]
If it works easily I'm happy to keep it, lets see how travis feels...

**Comment by alexpearce** [comment]
Oh yeah I forgot the `quiet_mode` thing. Well whatever, drop it :-1:

**Comment by dominikmuller** [comment]
What root 6 specific stuff are they using?

**Comment by alexpearce** [comment]
I thought they were using some Cling stuff? Could be mistaken.

@chrisburr Were you able to run the unit tests under Python 3?

**Comment by chrisburr** [comment]
I never thought to try them. I'm currently updating root on my VM so I can try after that has completed.

**Comment by dominikmuller** [comment]
It works in both versions. They didn't change the interface for building dicts

**Comment by alexpearce** [comment]
Looks good to me :+1:

**Pull request merged**
