### PR TITLE
Add studies folder with study scripts.

### PR DESCRIPTION
**Pull request by alexpearce**
See #96. If they work on `master`, feel free to add your own scripts.

### CODE REVIEW

**Comment by dominikmuller** [comment]
Quick question: Can we deactivate travis for this? Would save me the pain of having to fix a lot of formatting problems.

**Comment by alexpearce** [comment]
Well of course you should be formatting your scripts perfectly :wink: 

The [flake8](https://pypi.python.org/pypi/flake8) module is [only run on `analysis/charmproduction`](https://github.com/alexpearce/CharmProduction/blob/master/.travis.yml#L26), so the stuff in `analysis/studies` won't be checked.

**Comment by alexpearce** [comment]
Does anyone have anything they'd like to add before I merge this in a couple of hours?

**Comment by chrisburr** [comment]
I'm happy for you to go ahead and merge it.

**Pull request merged**
