### PR TITLE
Add paths and fix D0 variables for the Dst modes

### PR DESCRIPTION
**Pull request by chrisburr**
This is still missing a path somewhere but its mostly ready.

### CODE REVIEW

**Comment by alexpearce** [comment]
Thanks! I would like to add a test that checks that all the variables required by the derived classes, like `D0Tohh`, is present somewhere, either in `CharmProductionNtuple.mother_vars` or similar. Just working on it now.

**Comment by chrisburr** [comment]
I think this now work so merge whenever you're happy.

**Comment by alexpearce** [comment]
Should the `Dst` modes have a `variable` member defining the BDT inputs?

**Comment by chrisburr** [comment]
Yes it should, I'll fix it in a moment

**Comment by chrisburr** [comment]
Everything should be fixed. If you have any D0 data downloaded it needs redownloading after b74443c as the MagUp MC was actually MagDown.

**Comment by alexpearce** [comment]
I've added the tests in #68 so I think this can be merged.

**Pull request merged**
