### PR TITLE
Fix Travis errors

### PR DESCRIPTION
**Pull request by alexpearce**
Everything was working fine in #44, but then once it was merged the [tests failed](https://travis-ci.org/alexpearce/CharmProduction/builds/49626569).

Will try fixes in this PR.

### CODE REVIEW

**Comment by chrisburr** [comment]
Eagerly waiting to hear about 1cded9f

**Comment by alexpearce** [comment]
Apparently it works. How much do we want to bet that things will break again once it's merged?

**Comment by chrisburr** [comment]
This much: :moneybag: :money_with_wings: :dollar:

**Comment by alexpearce** [comment]
I restarted the build to double check and it's OK... Merge?

**Comment by chrisburr** [comment]
:+1:

**Pull request merged**
