### PR TITLE
Fitting

### PR DESCRIPTION
**Pull request by alexpearce**
Two months later...

I have a [few](https://github.com/alexpearce/CharmProduction/issues/18) [~~more~~](https://github.com/alexpearce/CharmProduction/issues/31) [~~things~~](https://github.com/alexpearce/CharmProduction/issues/32) I'd like to finish before merging, and [some](https://github.com/alexpearce/CharmProduction/issues/28) [other](https://github.com/alexpearce/CharmProduction/issues/29) [things](https://github.com/alexpearce/CharmProduction/issues/33) that can wait to have their own features branches, but the fitting framework is ready to be tested by everyone.

This won't be a completely clean merge as [`ntuples.py`](https://github.com/alexpearce/CharmProduction/blob/73f56e45281145fbeac4fd1a6064a4528762eb75/analysis/charmproduction/ntuples.py) as been split per-mode in [`ntuples/` on `analysis`](https://github.com/alexpearce/CharmProduction/tree/f0777a78d5278063fe796f7ee6a5ca7dce010328/analysis/charmproduction/ntuples), but it shouldn't be too much work.

## Testing

The [`fitting.py` script](https://github.com/alexpearce/CharmProduction/blob/73f56e45281145fbeac4fd1a6064a4528762eb75/analysis/fitting.py) is essentially the user guide on how to use the fitting framework. Currently, it can perform a 2D fit in mass and log<sub>10</sub>(IP χ<sup>2</sup>) simultaneously in pT-y bins, saving a bunch of plots in `analysis/output/`. It should be able to to the same in 3D in a couple of upcoming commits. Paths to ntuples are sort-of hardcoded.

What would be useful would be for you to test the fitting on your modes, using 2011 collision data and Monte Carlo. The MC data can be cheated or stripped, maybe the most useful is fully selected but I'd need to think about that. If there's something that's not clear or doesn't work how you'd expect, I'll consider it a bug.

### CODE REVIEW

**Comment by alexpearce** [comment]
I have gone and *slightly* screwed up by merging `master` in to `fitting`, so merging with `analysis` will effectively merge `master` in to `analysis`.

…

**Comment by chrisburr** [comment]
That needed to be done so :+1:

**Comment by alexpearce** [comment]
I think this is ready to merge. If there aren't any major comments I'll merge tomorrow morning.

**Comment by chrisburr** [comment]
I think it would be nice if `ntuples.py` was split up to make merging `analysis-bdt` easier.

**Comment by alexpearce** [comment]
But I guess once during the merge, I'll get merge conflicts because of that? So I can split up `ntuples.py` then? Or do you think it would just be easier/cleaner to make a commit with the splitting before the merge?

**Comment by chrisburr** [comment]
I didn't notice this isn't already in a merged state with `analysis`. I'm not sure, it depends if it will be easier to merge `analysis-bdt`+`analysis-without-magic` into `fitting` or vise versa.

**Pull request merged**
